### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by ejkkan** [jonathanpalma/react-native-tesseract-ocr#115]
**Is your feature request related to a problem? Please describe.**
Do you have any plans or timeline as when your thinking of bringing in iOS support for this library?

**Describe the solution you'd like**
Same functionality over both Android and iOS

**Comment by busykid** [comment]
ios working?

**Comment by Noitidart** [comment]
@busykid I don't think so. I didn't try, but the readme says ios only.

**Comment by theneekz** [comment]
It's not but I'd like to contribute. I have linked the ios native module into react native before, but I don't know if I need to support all of the methods that this package already seems to support for android:
```  
export interface ITesseractOcrModule {
    clear(): void;
    recognize(
      imageSource: string,
      lang: Lang,
      options?: Options
    ): Promise<string>;
    recognizeTokens(
      imageSource: string,
      lang: Lang,
      options?: Options
    ): Promise<string>;
    stop(): Promise<Token[]>;
  }
```

**Comment by albertbuchard** [comment]
https://reinteractive.com/posts/442-bringing-tesseract-to-mobile-with-react-native

**Comment by theneekz** [comment]
> https://reinteractive.com/posts/442-bringing-tesseract-to-mobile-with-react-native 

This is actually the post I used in order to set it up. I have a project that can run it, I'm just not sure how to get that work into this package. I know the methods available are different for one. Another major difference is that i can only use English on the iOS project.

**Comment by Macilias** [comment]
I know its stated that iOS is not supported yet, but its obviously planned since 2 Years and no progress there, do you need some particular help?

Currently the exception is:
`[TypeError: null is not an object (evaluating '_reactNativeTesseractOcr.default.recognize')]`

so it looks like some default has not been set there but what else?

**Comment by theneekz** [comment]
Currently there is nothing linked for iOS. I know how to implement the solution like in the article mentioned above but it would not match the android solution already used in this package (the methods are named differently and the article only teaches you how to set it up in English). I also don't see how to integrate it into this repo, that's something I need to spend more time on/get help with.

**Comment by Macilias** [comment]
Well additional models for other languages can be found here: https://github.com/tesseract-ocr/tessdata/tree/bf82613055ebc6e63d9e3b438a5c234bfd638c93

There is also an different project aiming the same target: https://github.com/zsajjad/react-native-text-detector
But it seams to be dead since it was updates for years now, but it would be great to have an module for OCR for react-native and this involves both, android AND iOS, so please tell we how we can help you out there!
