### ISSUE TITLE
Failed to install the app.

### ISSUE THREAD

**Issue by sparklaunch** [jonathanpalma/react-native-tesseract-ocr#146]
After the installation, I tried "yarn android" to build the app and it failed with the message saying, "Plugin with id 'maven' not found".

 - react: 18.1.0.
 - react-native: 0.70.6.
 - react-native-tesseract-ocr: 2.0.3.

**To Reproduce**
1. yarn add react-native-tesseract-ocr.
2. npx pod-install.
3. yarn android.

**Expected behavior**
Successful build for Android.

**Screenshots**
![스크린샷 2023-01-03 오전 8 46 35](https://user-images.githubusercontent.com/34114794/210285404-b9672b8a-dd76-4065-a8a5-214892a90146.png)

**Smartphone (please complete the following information):**
 - Samsung Galaxy Note 10+ (SM-N976N).
 - OS: Android 12 (SDK 30).

**Additional context**
![스크린샷 2023-01-03 오전 8 48 51](https://user-images.githubusercontent.com/34114794/210285482-a3341f18-50c3-4076-97a3-8f1197ee8a85.png)

**Comment by DiguinhoLNS** [comment]
Some news about this issue? I got the same bug in my app.

**Comment by sparklaunch** [comment]
It's been a couple of weeks and nobody seems to even care about it.

**Comment by esmailbenmoussa** [comment]
@sparklaunch or @DiguinhoLNS, did you manage to find a workaround or have you tried another ocr-lib?

**Comment by DiguinhoLNS** [comment]
I have tried a new lib, rn-text-detector

**Comment by Aszurar** [comment]
Has anyone managed to resolve the issue? Does this other rn-text-detector lib you tested work? I'm after trying to make this functionality also in an app.
I got it using the Google Vision API, but I'm looking for something that doesn't use the internet

**Comment by killatsignlife** [comment]
This issue is related to [#142](https://github.com/jonathanpalma/react-native-tesseract-ocr/issues/142).

**Comment by Aszurar** [comment]
I managed to put text recognition on images in my app.

I was able to do this for the first time using Google's cloud service, the Google Vision API
It is a free service with up to 1000 uses per month, after which it becomes paid.

Today I use the Google ML Kit installed directly on the device, it works offline and is completely free.
The Google Vision API today turns out to be the most accurate cloud version of the Google ML kit.

For those who want to know how to use Google Vision, it's very simple, **just make an API call sending your image via base64 and it returns an object with various information about the text in it**, including an attribute with all the text at once
**You need to create a service on Google Cloud Platform and add a payment method.**
https://blog.logrocket.com/build-text-detector-react-native/
remember, you need to add a payment method, this is not in the tutorial above, otherwise, everything is the same.


I'm using Google ML Kit with Text Recognizer module.
https://developers.google.com/ml-kit/guides
https://developers.google.com/ml-kit/vision/text-recognition

For those unfamiliar, it's a mobile SDK that brings Google's machine learning expertise to Android and iOS apps. Use our easy-to-use Vision and Natural Language APIs to solve common app challenges or create new user experiences. All use Google's best ML models and are offered at no financial cost.

All ML Kit APIs run on the device, enabling real-time use cases where you want to process a live camera feed, for example. It also means the functionality is available offline.

There are 2 ways to use it:
1. Installing via Firebase: https://github.com/invertase/react-native-firebase/tree/main/packages/ml

2. Installing by some lib that implements the settings automatically: 
There are several that try to do this, but many are deprecated, I'm using this one:
react-native-ml-kit
https://github.com/a7medev/react-native-ml-kit/tree/main/text-recognition

As I said above, I didn't install it via firebase, in this case **I used this react-native-ml-kit**.
Because I found it very simple to use, I didn't get to test it by installing it via firebase.


```js
import TextRecognition from '@react-native-ml-kit/text-recognition';

const result = await TextRecognition.recognize(imageURL);

console.log('Recognized text:', result.text);

```
