### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by marko89kv** [jonathanpalma/react-native-tesseract-ocr#4]
Hi, when I tried to install the library with `npm install react-native-tesseract-ocr --save`, I got an error:

```
├── UNMET PEER DEPENDENCY react-native@0.34.1
└── react-native-tesseract-ocr@1.0.4 
```

my `react-native` version was 0.34, so I've updated it to 0.34.1, and the result is the same.

**Comment by jonathanpalma** [comment]
@marko89kv Hey man!! I appreciate your support opening an issue. I tried to replicate the error but it looks like is just a warning 

```
npm WARN react-native-tesseract-ocr@1.0.4 requires a peer of react-native@^0.29.0 but none was installed.
```

that is caused by npm when `react-native-tesseract-ocr` peerDependencies are missing on your project. But considering that when you install this lib you're already using a version of `react-native` on your project, so I decided to remove the peerDependencies and publish changes as version 1.0.5 on npm.
