### ISSUE TITLE
undefined is not an object (evaluating '_reactNativeTesseractOcr2.default.recognize')

### ISSUE THREAD

**Issue by houdzaiw** [jonathanpalma/react-native-tesseract-ocr#42]
iOS Error after selecting picture
 undefined is not an object (evaluating '_reactNativeTesseractOcr2.default.recognize')

**Comment by scribblink** [comment]
I have not found a solution but the issue is that react-native-image-picker does not have path node in response object on ios.

**Comment by JKLTechno** [comment]
+1 
Same issue for me also

**Comment by paulohlips** [comment]
I have the same problem, some solution?

**Comment by Josh-Rosen** [comment]
I'm having the same issue.  Are any of you using Expo?

**Comment by httol** [comment]
Same issue for me, any solutions?

**Comment by alexalv** [comment]
I was able to solve my problem by removing expo and using pure react-native. Sadly I had to rewrite parts which were using expo, as `expo eject` generated android app that produced strange compile and runtime errors (this one for example https://forums.expo.io/t/cannot-run-on-android-device/11160)

I suppose problems in my case happened because the native part of the library was not compiled and/or added to app (or was not compiled correctly) through expo dev tools, although I have not found proof of that just yet.

**Comment by tuicodemobile** [comment]
I face same issue.
I think problem is React-native can not connect to native, so can not found recognize funtion.
