### ISSUE TITLE
Error : Data path does not exist

### ISSUE THREAD

**Issue by Altercode99** [jonathanpalma/react-native-tesseract-ocr#47]
What this can happened ?

this is my code

`takePicture = async function() {
        if (this.camera) {
            const options = { quality: 0.5, base64: true };
            const data = await this.camera.takePictureAsync(options)
            console.log(data.uri);
            this.setState({path: data.uri});
            const tessOptions = {
                whitelist: null, 
                blacklist: '1234567890\'!"#$%&/()={}[]+*-_:;<>'
            };
            RNTesseractOcr.recognize(data.uri, 'LANG_ENGLISH', tessOptions)
                .then((result) => {
                // this.setState({ ocrResult: result });
                console.log("OCR Result: ", result);
                })
                .catch((err) => {
                console.log("OCR Error: ", err);
                })
                .done();
        }
    };`

this is the error

OCR Error:  Error: Data path does not exist!
    at createErrorFromErrorData (D:\React Native\alternote\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:121)
    at D:\React Native\alternote\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:78
    at MessageQueue.__invokeCallback (D:\React Native\alternote\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:398)
    at D:\React Native\alternote\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:137
    at MessageQueue.__guardSafe (D:\React Native\alternote\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (D:\React Native\alternote\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:136)
    at debuggerWorker.js:70

i put my tess data in src/main/assets/tessdata but not working

**Comment by muhammadnasir786** [comment]
same here ! +1

**Comment by jonathanpalma** [comment]
@Altercode99 @nasir03082409229  @dass2808 could you please provide the name and the version of the library that you're using to take the picture?

**Comment by SwagatRanjit84** [comment]
@idgafl7 Have you solved the issue?

**Comment by SwagatRanjit84** [comment]
OCR Error:  Error: Data path does not exist!
    at createErrorFromErrorData (C:\reactnativeapp\ocr\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:146)
    at C:\reactnativeapp\ocr\node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:95
    at MessageQueue.__invokeCallback (C:\reactnativeapp\ocr\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:414)
    at C:\reactnativeapp\ocr\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:127
    at MessageQueue.__guard (C:\reactnativeapp\ocr\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (C:\reactnativeapp\ocr\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:126)
    at debuggerWorker.js:72


Data path is :  file:///storage/emulated/0/documents/a.jpg which is absolutely correct

**Comment by nasir03082409229** [comment]
@jonathanpalma I am Using react-native-camera for taking picture

**Comment by SwagatRanjit84** [comment]
@nasir03082409229 What should be the data path? file:///storage/emulated/0/documents/a.jpg  or var RNFS = require('react-native-fs');
  const imgPath ='file://' + RNFS.DocumentDirectoryPath + '/a.jpg'
DIdn't work for both cases

**Comment by SwagatRanjit84** [comment]
@nasir03082409229  @jonathanpalma  @Altercode99 @dass2808  @idgafl7 @aphex3k 
Has anyone got this problem solved out?

**Comment by antonbelev** [comment]
I'm having the same issue.

**Comment by anapetrescu** [comment]
Same here. Has anyone solved this problem?

**Comment by ziyafenn** [comment]
Still no idea why this is happening?

**Comment by nasseh101** [comment]
same here

**Comment by SwagatRanjit84** [comment]
Anyone found the solution?

**Comment by SwagatRanjit84** [comment]
@ziyafenn Where to drop those trained files?

**Comment by vmvini** [comment]
I had the error 'Data path does not exist' when I was using the lang parameter as 'LANG_PORTUGUESE'. 
I changed the lang parameter to RNTesseractOcr.LANG_PORTUGUESE and it worked, but I got another 
error: '"Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference"'
I think this second error is due to the way Im requesting my image
`
import RNTesseractOcr from 'react-native-tesseract-ocr';
RNTesseractOcr
    .recognize('./image.png', RNTesseractOcr.LANG_PORTUGUESE, tessOptions)
    .then((result) => {
      debugger;
    })
    .catch((err) => {
      debugger;
    })
    .done();
`

**Comment by vmvini** [comment]
I had this same error 'Data path does not exist'. When investigating the source code, this error is thrown by the TessBaseAPI.init(String datapath, String language)  method, so its not related to the image path, its related to the tessdata path. 

init is called as tessBaseApi.init(DATA_PATH, getConstants().get(lang).toString());
DATA_PATH is defined on the class RNTesseractOcrModule in this line:
`
private static String DATA_PATH = Environment.getExternalStorageDirectory().toString() + File.separator
`

So, its not accessing the assets folder within our project because its impossible for a library to do it without context, its accessing directly through the external storage path, concatenating later to the project's name: 
`
Environment.getExternalStorageDirectory().toString() + File.separator +  reactContext.getPackageName() + File.separator
` 
which evaluates to: /storage/emulated/0/com.projectsname/

The folder `/storage/emulated/0/com.projectsname/` is there when I open on my pc, but later the TessBaseAPI code executes:
`
if (!datapathFile.exists())
            throw new IllegalArgumentException("Data path does not exist!");
`
And cant find the folder...
So, I dont know why it didnt find the `/storage/emulated/0/com.projectsname/`. 
And inside the `/storage/emulated/0/com.projectsname/`, the folder 'tessdata' is not there also even though I placed the tessdata folder inside android/app/src/main/assets/

But, I could do the tesseract work changing DATA_PATH to :
`
private static String DATA_PATH = Environment.getExternalStorageDirectory().toString() + File.separator + Environment.DIRECTORY_DOWNLOADS + File.separator;
`

then I commented the line that concatenates the path with the projects directory :
`
public RNTesseractOcrModule(ReactApplicationContext reactContext) {
		super(reactContext);
		this.reactContext = reactContext;
		//if (!this.DATA_PATH.contains(reactContext.getPackageName()))
		//	this.DATA_PATH += reactContext.getPackageName() + File.separator;
	}
`
And finally, I moved my tessdata to my android downloads folder.

Its not the solution I want, but at least I could do the tesseract work, later I will try something else.

**Comment by bernzJ** [comment]
I ran into this,
**Solution**:
Give your installed app the storage write permission either directly into your emulator/phone app's permission manager or throughout gradle/app intents.

**Comment by jonathanpalma** [comment]
Trained data files should be placed under `android/app/src/main/assets/tessdata`, please make sure that this files look like `eng.traineddata`, `spa.traineddata`, `fra.traineddata`, etc...

In case you have any questions you can have a look at the example which contains a `.gitkeep` file to show you where to drop your trained data files.

https://www.github.com/jonathanpalma/react-native-tesseract-ocr/tree/master/example%2Fandroid%2Fapp%2Fsrc%2Fmain%2Fassets%2Ftessdata

I would like to mention that many of the path issues has been solved an released as part of v2.0.0. However, I haven't tried `react-native-camera` but I've done many successful tests using `react-native-image-picker` and `react-native-image-crop-picker`

Please give it a try and feel free to open a new issue in case you find any bug
