### ISSUE TITLE
tess-two project is Archived

### ISSUE THREAD

**Issue by sytolk** [jonathanpalma/react-native-tesseract-ocr#67]
https://github.com/rmtheis/tess-two
its need to update native Android dependencies according to https://github.com/alexcohn/tess-two

**Comment by jonathanpalma** [comment]
Hi @sytolk, you are right @rmtheis's repository has been archived. However, since (as far as I know) @alexcohn's version hasn't been published in the registry yet, this project will continue using the latest version in the [maven repository](https://mvnrepository.com/artifact/com.rmtheis/tess-two?repo=jcenter)

**Comment by alexcohn** [comment]
I don't intend to publish *my version* in maven repository, but you can easily do it if you need

**Comment by jonathanpalma** [comment]
@alexcohn thanks for replying, I have never published a package in Maven repository but will do my research in order to assess whether investing effort on it provides enough value considering the limited amount of time I can currently spend on this project. Would you be able to have a quick chat to understand the current state of your version?

**Comment by alexcohn** [comment]
@jonathanpalma I will be glad to provide any help necessary, but I don't remember much about this. Maybe you can get better collaborator in @gregko, who is currently working on version 4.1.1: https://github.com/gregko/tess-two
